### ISSUE TITLE
New methods for eSIM ph2

### ISSUE THREAD

**Issue by amegias** [Telefonica/webview-bridge#114]
Due to [this spec](https://telefonicacorp.sharepoint.com/:w:/s/Colabora_TCX/ETZmafsFX-9OrYe1b51zXjkByyFFIOtlfU_G53QSHsmAYg?e=6MeBuB&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMzA3MDMwNzMzOSIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D&wdOrigin=TEAMS-ELECTRON.teams.chiclet&wdExp=TEAMS-CONTROL&wdhostclicktime=1692174040309&web=1), we need to expose several methods through the bridge:

# Get device model
```typescript
getDeviceModel: () => Promise<{model: string}>
```

```
Request → {type: "MODEL", id: string} 
Response → {type: "MODEL", id: string, payload: {model: string}} 
```
It will return a model like `SAMSUNG-SM-G930A`, `iPhone9,3`, ...

See:
* https://developer.android.com/reference/android/os/Build#MODEL
* https://www.innerfence.com/howto/apple-ios-devices-dates-versions-instruction-sets

# Get Esim Info
```
getEsimInfo: () => Promise<{supportsEsim: boolean, eid?: string}>;
```

```
Request → {type: "GET_ESIM_INFO", id} 
Response → {type: "GET_ESIM_INFO", id, payload: {supportsEsim: false, eid?: "1234"}} 
```
eid is optional and only available in Android

# Request Device IMEI
implement the following method (already existing in the bridge) only for Android
```
requestDeviceImei: () => Promise<{imei: string}>
```

```
Request → {type: "IMEI", id} 
Response → {type: "IMEI", id, payload: {imei: "1234"}} 
``` 

# Deprecations

Mark as deprecated in webview-bridge

* `requestSimIcc`
* `requestSimImsi`

**Comment by nimeacuerdo** [comment]
MODEL method in Android is already implemented and returns https://developer.android.com/reference/android/os/Build#MODEL

**Comment by amegias** [comment]
> MODEL method in Android is already implemented and returns https://developer.android.com/reference/android/os/Build#MODEL

Then, could you specify the method here please? Just to know the name, payload, result, etc and implement it in iOS

**Comment by pladaria** [comment]
I would name this method as "getDeviceModel"

**Comment by nimeacuerdo** [comment]
> I would name this method as `getDeviceModel: () => Promise<{model: string}>`
> 
> @amegias according to the (now deprecated) [document](https://telefonicacorp.sharepoint.com/:w:/r/sites/Colabora_TCX/_layouts/15/Doc.aspx?sourcedoc=%7BEDD03AE1-B357-4F30-8128-69B8A8D167DD%7D&file=WebView%20Bridge.docx&action=default&mobileredirect=true&cid=03aac2ee-7269-4cef-887e-577b8c1bd54f)
> 
> ```
> Request → {type: "MODEL", id} 
> Response → {type: "MODEL", id, payload: {model: "One Touch Easy"}} 
> ```
> 
> @nimeacuerdo please, confirm that Android implementation follows this description

Yes, that's what we have in Android right now.

**Comment by nimeacuerdo** [comment]
What about this for the other two methods?

```
getDeviceImei: () => Promise<{imei: string}>
Request → {type: "IMEI", id} 
Response → {type: "IMEI", id, payload: {imei: "1234"}} 
```

```
getDeviceEid: () => Promise<{eid: string}>
Request → {type: "EID", id} 
Response → {type: "EID", id, payload: {eid: "1234"}} 
```

**Comment by pladaria** [comment]
@nimeacuerdo 

the webview bridge already has a `requestDeviceImei` method using the `IMEI` message type.

https://github.com/Telefonica/webview-bridge/blob/master/src/device.ts#L15

I guess no one is using it so we could deprecate it and implement it using the getXxx naming.

Device/SIM related methods already implemented by the webview bridge are:

* `requestSimIcc`: 0 uses in webapp
* `requestSimImsi`: 0 uses in webapp
* `requestDeviceImei`: 0 uses in webapp
* `getEsimInfo`: 1 usage in webapp: https://github.com/Telefonica/webapp/blob/master/web/src/common/webview/native-utils.tsx#L188

What is `getEsimInfo` returning? Is it already providing the EID?
Should we deprecate all unused methods? which ones are already implemented in iOS/Android

**Comment by nimeacuerdo** [comment]
Only `GET_ESIM_INFO` is currently implemented on Android.

Regarding `eid`, it is pretty specific to **eSIM** so it could make sense to add it to the existing `getEsimInfo` response as additional data.

**Comment by amegias** [comment]
> Only `GET_ESIM_INFO` is currently implemented on Android.
> 
> Regarding `eid`, it is pretty specific to **eSIM** so it could make sense to add it to the existing `getEsimInfo` response as additional data.

but the field must be optional since iOS won't send it. No problems from the iOS side.

Could you edit my first comment with the proposal @nimeacuerdo ?

**Comment by nimeacuerdo** [comment]
> > Only `GET_ESIM_INFO` is currently implemented on Android.
> > Regarding `eid`, it is pretty specific to **eSIM** so it could make sense to add it to the existing `getEsimInfo` response as additional data.
> 
> but the field must be optional since iOS won't send it. No problems from the iOS side.
> 
> Could you edit my first comment with the proposal @nimeacuerdo ?

Done, let me know if it's ok for everyone @pladaria @amegias
