### ISSUE TITLE
New methods for customers image management

### ISSUE THREAD

**Issue by rubygroovy** [Telefonica/webview-bridge#124]
Due to [this spec](https://confluence.tid.es/pages/viewpage.action?spaceKey=CTO&title=Tech+Spec%3A+New+new+app+-+Perfil+tab) we need to to expose the following methods through the bridge:

### getProfileImage
an operation to fetch the photo that the user has uploaded previously, if any.

- This operation will not have any input parameter
- The operation will return a nullable base64 image (null in case the user has not selected any picture previously).
- Message type: GET_PROFILE_IMAGE
- Response model: {"image": String?}

### startProfileImageFlow
an operation to initiate the flow to edit the user's profile photo.

- This operation will not have any parameter. In case the user had previously selected a picture as his profile photo the user will be shown a bottom-sheet menu with the options: "Ver foto de perfil", "Abrir cámara", "Elegir de la galería" and "Eliminar foto de perfil". In case there is not any picture selected as the user's profile photo the options of the menu will be "Abrir cámara" and "Elegir de la galería".
- The operation will return 3 possible values: a base64 image in case the user selects a new picture, a null in case the user selects the option "Elimiar foto de perfil" and a "cancelled" value in case the user cancels the flow.
- Message type: START_PROFILE_IMAGE_FLOW
- Response model: {"isCancelled": true|false, "image": String?}

**Comment by pladaria** [comment]
```ts
{
    status: 'updated' | 'removed' | 'cancelled',
    image?: stringBase64 | null
}
```

When the flow is cancelled but the user already had an image, the image should return the current image

**Comment by atabel** [comment]
https://jira.tid.es/browse/APPS-8097

**Comment by atabel** [comment]
@rubygroovy, are we on time to change the definition with @pladaria suggestion? or is the native development already closed? please, can you link iOS/Android tickets here?

**Comment by ieduardogf** [comment]
All of this is on the native apps since version 14.9 I think (December 2023). 
https://jira.tid.es/browse/IOS-9557
https://jira.tid.es/browse/ANDROID-14015

**Comment by rubygroovy** [comment]
The native developments tickets are https://jira.tid.es/browse/IOS-9557 and https://jira.tid.es/browse/ANDROID-14015, both of them already closed.
