### ISSUE TITLE
New method to retrieve if user has Pincode activated.

### ISSUE THREAD

**Issue by dagonco** [Telefonica/webview-bridge#125]
Based on the migration from Profile to the web, from the native part it must be exposed through the bridge whether the user has Pincode activated or not. [Link to the PRD](https://telefonicacorp.sharepoint.com/:w:/r/sites/Colabora_TCX/Shared%20Documents/CX/Product%20docs/00_OB%20Product/OB_%20Spain/Nueva%20App/New%20App%20-%20Tab%20de%20perfil%20(settings).docx?d=wdbf6f848cc8a41318bf4e577239a9423&csf=1&web=1&e=zkFzOC&nav=eyJoIjoiOTg3MjUwMDgxIn0%3D).

### Get Pincode Info
```typescript
getPincodeInfo: () => Promise<{status: "enabled" | "disabled"}>
```
```
Request → {type: "GET_PINCODE_INFO", id: string} 
Response → {type: "GET_PINCODE_INFO", id: string, payload: {status: "enabled" | "disabled"}}
```

> [!NOTE]
> Any status different than "enabled" (like unknown, not supported, etc) will be reported as "disabled"

**Comment by DavidMarinCalleja** [comment]
Hi, we were discussing in the team about this bridge method and the comment came up to try to give a more generic/scalable solution. I mean that instead of returning a boolean value maybe we could be interested in something more generic like an enum where initially the values could be:
```
enum {
   case PIN_ENABLED
   case PIN_DISABLED
}
```
I do not have current uses cases but perhaps in the future we might be interested in returning in this function values like: 
```
PIN_NOT_SUPPORTED
PIN_AND_BIOMETRY_IS_ENABLED
```

**Comment by amegias** [comment]
> Hi, we were discussing in the team about this bridge method and the comment came up to try to give a more generic/scalable solution. I mean that instead of returning a boolean value maybe we could be interested in something more generic like an enum where initially the values could be:
> 
> ```
> enum {
>    case PIN_ENABLED
>    case PIN_DISABLED
> }
> ```
> 
> I do not have current uses cases but perhaps in the future we might be interested in returning in this function values like:
> 
> ```
> PIN_NOT_SUPPORTED
> PIN_AND_BIOMETRY_IS_ENABLED
> ```
> 
> **Updated**: I upload a sample response
> 
> > Response -> {type: "GET_PINCODE_INFO", payload: {"status": "PIN_ENABLED"}}

Agree with @DavidMarinCalleja 

Btw, I would simplify the tokens:
`Response -> {type: "GET_PINCODE_INFO", payload: {"status": "enabled" | "disabled"}}`
> [!NOTE]
> `disabled` for any unknown `status`

**Comment by dagonco** [comment]
Sure, that looks much better! We could go that way, thanks! 🚀

**Comment by pladaria** [comment]
LGTM

Please, specify the possible status values in the functions return type:
```ts
getPincodeInfo: () => Promise<{status: "enabled" | "disabled"}>
```

Minor thing: the `id` was missing in the response:
```ts
Request → {type: "GET_PINCODE_INFO", id: string} 
Response → {type: "GET_PINCODE_INFO", id: string, payload: {"status": "enabled" | "disabled"}}
```

**Comment by atabel** [comment]
LGTM. Jira ticket for web implementation: https://jira.tid.es/browse/WEB-1760
