### ISSUE TITLE
New method to get TAC identifier

### ISSUE THREAD

**Issue by jeslat** [Telefonica/webview-bridge#127]
Due to [this spec](https://telefonicacorp.sharepoint.com/:w:/s/Colabora_TCX/Eft6wfLnbUNCqC434JUSIhoBU-0RoDAugM5FiWbB7wR39Q?e=2wrvXE) from Vivo, we need to add a new method to get [TAC identifier](https://en.wikipedia.org/wiki/Type_Allocation_Code). This method will be available only in Android because we can't obtain this information in iOS.

As this information is available starting Android 10, we will return a `null` value if it's not available in that device.

The [TAC identifier](https://en.wikipedia.org/wiki/Type_Allocation_Code) is the first 8 digits of the IMEI. We already have a method to get the IMEI but to obtain this value, we need carrier privileges permission which in many cases we don't have. To get the TAC we don't need any special permission because it only identifies the device model, not the device itself.

### Get TAC identifier
```typescript
getDeviceTac: () => Promise<{tac: string | null}>
```
```
Request → {type: "TAC", id: string} 
Response → {type: "TAC", id: string, payload: {tac?: "1234"}}
```

**Comment by atabel** [comment]
LGTM, but I'd rename it to `getDeviceTac`. I know we use `request` prefix for `requestDeviceImei`, but most of the bridge methods have the `getXXX` naming convention.

**Comment by atabel** [comment]
https://jira.tid.es/browse/WEB-1800
