### ISSUE TITLE
Add new method to request Pin/Biometric authentication from bridge

### ISSUE THREAD

**Issue by dpastor** [Telefonica/webview-bridge#129]
Due this [spec](https://telefonicacorp.sharepoint.com/:w:/r/sites/Colabora_TCX/_layouts/15/Doc.aspx?sourcedoc=%7B03FB52A4-9351-4342-91D7-38028F5C576C%7D&file=Shared%20Spec%20%25u2013%20OBVIVO-2099%20-%20Parcela%20PIX%20Face%20ID.docx&nav=eyJjIjo0MzgzMjE0NDV9&action=default&mobileredirect=true), we need to provide the following bridge method:

### Trigger Pin/Biometric Authentication
This method allows triggering Pin/Biometric authentication if necessary, taking into account 3 possible scenarios:
1. User has Pin/Biometric already configured in the app
    - Last previous authentication (or last pin/biometric setup) is still valid. 
      - Nothing will be presented to user and bridge method will success.
    - Last previous authentication (or last pin/biometric setup) is not valid.
      - Authentication will be required, blocking the user until it is performed.
2. In any other case:
    - User will be taken to the Pin/Biometric screen to enable any authentication method.
      - In case user leaves the configuration screen without providing an authentication method, bridge method will fail with 401 code.
      
### Js method

```javascript
triggerPinOrBiometricAuthentication: ({
    maxSecondsSinceLastValidation: number;
}) => Promise<{
    result: 'USER_AUTHENTICATED' | 'USER_ENABLED_AUTHENTICATION' | 'LAST_AUTHENTICATION_STILL_VALID';
}>
```

#### Message type

`TRIGGER_PIN_OR_BIOMETRIC_AUTHENTICATION`

#### Request Payload

- `maxSecondsSinceLastValidation: number`
    - If time elapsed since last authentication is less than the number of seconds specified here, authentication will succeed without requesting it again
    
#### Success Response Payload

`result: 'USER_AUTHENTICATED' | 'USER_ENABLED_AUTHENTICATION' | 'LAST_AUTHENTICATION_STILL_VALID'`

#### Error response codes

**401** → Unauthorized

**Comment by dpastor** [comment]
> @dpastor, should we have a default value for `maxSecondsSinceLastValidation`?

No, Vivo will just always set time they want.

**Comment by marcoskolodny** [comment]
Small question @dpastor: what is the minimum required App version that supports this method?
