### ISSUE TITLE
Evolution of "MESSAGE" event (Snackbar)

### ISSUE THREAD

**Issue by jeslat** [Telefonica/webview-bridge#132]
We need to be able to customize the button content description (text that is talked by the device when the accessibility is enabled). We should add a new optional parameter to the method to set the button content description.

This requirement comes from Vivo https://www.figma.com/design/fjGgzSH1zdCTxAxMfOEUma/Menu-Mais?node-id=1197-324696&t=o0PMTgO238G06o57-0

<img src="https://github.com/Telefonica/webview-bridge/assets/2582348/a9acf131-3e46-42b1-85db-b5ac165fe062" alt="drawing" width="400"/>

### Current status
```
nativeMessage: ({
        message: string;
        duration?: 'PERSISTENT';
        buttonText?: string;
        type?: 'INFORMATIVE' | 'CRITICAL' | 'SUCCESS';
        withDismiss?: boolean;
}) => Promise<{
    action: 'DISMISS' | 'BUTTON' | 'TIMEOUT' | 'CONSECUTIVE';
}>;
```

### Proposed solution

Add a new optional field `buttonAccessibilityLabel`:
```
nativeMessage: ({
        message: string;
        duration?: 'PERSISTENT';
        buttonText?: string;
        buttonAccessibilityLabel?: string;
        type?: 'INFORMATIVE' | 'CRITICAL' | 'SUCCESS';
        withDismiss?: boolean;
}) => Promise<{
    action: 'DISMISS' | 'BUTTON' | 'TIMEOUT' | 'CONSECUTIVE';
}>;
```

**Comment by amegias** [comment]
Does `buttonContentDescription` mean the button's accessibility?

**Comment by dhidalgofadrique** [comment]
> Does `buttonContentDescription` mean the button's accessibility?

If so maybe a name mentioning "accessibility" would be more appropiate (like `buttonAccessibilityLabel` or something similar)

**Comment by jeslat** [comment]
> Does `buttonContentDescription` mean the button's accessibility?

Yes, it means the text that will be spoken by the device when the accessibility is enabled. In Android, "content description" is the name used for this information. If iOS is different, I'm ok with `buttonAccessibilityLabel`

**Comment by dhidalgofadrique** [comment]
> > Does `buttonContentDescription` mean the button's accessibility?
> 
> Yes, it means the text that will be spoken by the device when the accessibility is enabled. In Android, "content description" is the name used for this information. If iOS is different, I'm ok with `buttonAccessibilityLabel`

Oh, I thought Android naming included accessibility word. If so, no problem about using `buttonContentDescription` 😉

**Comment by jeslat** [comment]
No, if "content description" doesn't mean anything in iOS, I prefer to put `buttonAccessibilityLabel` that is clearer.

**Comment by amegias** [comment]
> No, if "content description" doesn't mean anything in iOS, I prefer to put `buttonAccessibilityLabel` that is clearer.

Yes please 😍 `buttonAccessibilityLabel`

**Comment by jeslat** [comment]
Description updated with `buttonAccessibilityLabel`

**Comment by atabel** [comment]
lgtm

**Comment by atabel** [comment]
https://jira.tid.es/browse/WEB-1906

**Comment by atabel** [comment]
@jeslat, @amegias, @dhidalgofadrique. Do you know the first app version supporting this? we need that to include in the docs
