### ISSUE TITLE
Add support for the `destructive` flag in native `confirm` dialog

### ISSUE THREAD

**Issue by carlosgarciaibanez** [Telefonica/webview-bridge#134]
For the _Session management_ functionality we will use a confirmation dialog to delete the sessions selected by the user. This dialog is based on the Mistica's `Confirm` component. This components admits a `destructive` flag that is used to tell the component that the primary action implies "destruction" of entities and thus should be displayed in a special way.

The web version of the component shows the primary button with a red color, like this:
![image](https://github.com/Telefonica/webview-bridge/assets/4517448/7a631646-9a17-42bf-b2e2-59c7c14cbaa6)

However, when used on a device by means of the webview bridge, the _destructive_ semantics are lost because the flag is ignored:
![image](https://github.com/Telefonica/webview-bridge/assets/4517448/3c3bc1ee-1354-4169-9f9f-6cb2b6b1e457)

Instead, we would expect the dialog to be displayed like this on iOS (when invoked with the `destructive` flag):
![image](https://github.com/Telefonica/webview-bridge/assets/4517448/e0473667-3eb6-4794-b3be-957ce0693f8a)

The general behavior of the component should not change, only its appearance when the flag is set to true.

**Comment by atabel** [comment]
### Current status:
```ts
nativeConfirm: ({
    message: string;
    title?: string;
    acceptText: string;
    cancelText: string;
}) => Promise<boolean>;
```

### Proposed solution:
```diff
nativeConfirm: ({
    message: string;
    title?: string;
    acceptText: string;
    cancelText: string;
+    destructive?: boolean;
}) => Promise<boolean>;
```

`destructive` is `false` by default.

### Retrocompatibility:
Old apps will ignore the new `destructive` attribute, so the `destructive` attribute won't have any effect. Newer apps will show the primary button (the one with the accept text) red when `destructive` is received as `true`.

**Comment by atabel** [comment]
web ticket: https://jira.tid.es/browse/WEB-1907

**Comment by jeprubio** [comment]
Which red colour should we use? Just pure red for all the brands? Or should it be a brand colour?

**Comment by nimeacuerdo** [comment]
> Which red colour should we use? Just pure red for all the brands? Or should we use colorError from the brand? @atabel

solved?

**Comment by jeprubio** [comment]
> > Which red colour should we use? Just pure red for all the brands? Or should we use colorError from the brand? @atabel
> 
> solved?

Yup, sorry, forgot the comment, it was discussed in design-appscore and decided to use textLinkDanger for this in the cases when it's not defined by the SO.
