### ISSUE TITLE
Show/Hide Loading Overlay

### ISSUE THREAD

**Issue by dpastor** [Telefonica/webview-bridge#145]
Due this [spec](https://confluence.tid.es/display/CTO/%5BAPPS%5D+Tech+Spec%3A+Tela+de+Loading), we need to provide the following 2 bridge methods:

## Show Loading Overlay

This method allows showing a fullscreen loading overlay following [this figma specification](https://www.figma.com/design/Via0lhrPKYB6DOQMbWcshO/Loading-animation?node-id=1-3&node-type=canvas&t=8rfucRUlSUQEaEy9-0)

All method parameters are optional, if method is called while a previous loading screen is being shown, it would return an error.

### Js method
```javascript
showLoadingOverlay: ({
    inAnimation?: boolean;
    outAnimation?: boolean;
    minimumLoopDurationMs?: number;
    stopAnimationCycle?: boolean;
    backgroundAnimation?: boolean;
    descriptions?: Array<string>;
    descriptionDurationMs?: number;
    timeoutMs?: number; // After this timeout loading screen would be hidden automatically
    closeOnBackButtonPressAfterFinish?: boolean; // (Only Android) If true, after loading screen has been hidden, if user presses android back button, webview window will close.
}) => Promise<void>
```

Default values (Just for documentation purposes, determined in native apps):

```
inAnimation --> false
outAnimation --> false
minimumLoopDurationMs --> 0
stopAnimationCycle --> true
backgroundAnimation --> false
descriptions --> []
descriptionDurationMs --> 3000
timeoutMs --> 20000
closeOnBackButtonPressAfterFinish --> true
```

Message type:

**SHOW_LOADING_OVERLAY**

Error response codes
- 503 --> Loading screen already showing.

## Hide Loading Overlay

This method allows hiding the fullscreen loading overlay previosuly mentioned.

In case it is called when the loading screen is not currently shown, it would have no effect.

### Js method
```javascript
hideLoadingOverlay = ( ) => Promise<void>
```

Message type:

**HIDE_LOADING_OVERLAY**

Error response codes
- No errors

**Comment by atabel** [comment]
@dpastor, we should document the default values of all the options when not provided

**Comment by atabel** [comment]
WEB ticket https://jira.tid.es/browse/WEB-2068

**Comment by dpastor** [comment]
> @dpastor, we should document the default values of all the options when not provided
> 
> ~what does `stopAnimationCycle` mean?~ (nevermind, already read in the figma spec)

Added to the issue description.

**Comment by dpastor** [comment]
> @dpastor, I think I'd remove this setting: ![image](https://private-user-images.githubusercontent.com/1849576/374207067-bb9d5b40-877e-4a1e-8998-214631e6b6bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNzI4MDcsIm5iZiI6MTcyODM3MjUwNywicGF0aCI6Ii8xODQ5NTc2LzM3NDIwNzA2Ny1iYjlkNWI0MC04NzdlLTRhMWUtODk5OC0yMTQ2MzFlNmI2YmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDhUMDcyODI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzE5YjM0Y2ExMDVjODI5NmJkMGNkNDJmOTQ4NzJmODMyZjUyMGViMTRmMTgwYjJjYjc1ZGE0NWI2NmEwMmI4MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ooRQoKAzmnGpo1acSEwDw23nt3dfmrOph9y8mgK9A2w)

This is actually a second animation that can be added to the "loop" step of the animation (already available with vivo assets, the waves), just following figma specification, but do you see any inconvenience with it?

**Comment by atabel** [comment]
> > @dpastor, I think I'd remove this setting: ![image](https://private-user-images.githubusercontent.com/1849576/374207067-bb9d5b40-877e-4a1e-8998-214631e6b6bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNzI4MDcsIm5iZiI6MTcyODM3MjUwNywicGF0aCI6Ii8xODQ5NTc2LzM3NDIwNzA2Ny1iYjlkNWI0MC04NzdlLTRhMWUtODk5OC0yMTQ2MzFlNmI2YmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDhUMDcyODI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzE5YjM0Y2ExMDVjODI5NmJkMGNkNDJmOTQ4NzJmODMyZjUyMGViMTRmMTgwYjJjYjc1ZGE0NWI2NmEwMmI4MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ooRQoKAzmnGpo1acSEwDw23nt3dfmrOph9y8mgK9A2w)
> 
> This is actually a second animation that can be added to the "loop" step of the animation (already available with vivo assets, the waves), just following figma specification, but do you see any inconvenience with it?

are you sure this param refers to waves animation? I thought it was intended to add a new custom one (which I don't think it's needed). In the case the spec is talking about the waves, what's the point on disabling them?

**Comment by dpastor** [comment]
> > > @dpastor, I think I'd remove this setting: ![image](https://private-user-images.githubusercontent.com/1849576/374207067-bb9d5b40-877e-4a1e-8998-214631e6b6bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNzI4MDcsIm5iZiI6MTcyODM3MjUwNywicGF0aCI6Ii8xODQ5NTc2LzM3NDIwNzA2Ny1iYjlkNWI0MC04NzdlLTRhMWUtODk5OC0yMTQ2MzFlNmI2YmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDhUMDcyODI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzE5YjM0Y2ExMDVjODI5NmJkMGNkNDJmOTQ4NzJmODMyZjUyMGViMTRmMTgwYjJjYjc1ZGE0NWI2NmEwMmI4MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ooRQoKAzmnGpo1acSEwDw23nt3dfmrOph9y8mgK9A2w)
> > 
> > 
> > This is actually a second animation that can be added to the "loop" step of the animation (already available with vivo assets, the waves), just following figma specification, but do you see any inconvenience with it?
> 
> are you sure this param refers to waves animation? I thought it was intended to add a new custom one (which I don't think it's needed). In the case the spec is talking about the waves, what's the point on disabling them?

@yceballost WDYT about this, this is also specified in the new Mistica component figma -> https://www.figma.com/design/KYdCKU8obcDapI8ihpsaWs/%F0%9F%94%B8-LoadingScreen-Specs?node-id=61-5988&node-type=frame&t=LReluuIKqauXRqQ3-0

In any case we currently have the wave animation separated from the loop animation in the native apps, so in any case we need to add 2 separate animations if we remove this flag.
