### ISSUE TITLE
New DOWNLOAD_BASE64 bridge method

### ISSUE THREAD

**Issue by dpastor** [Telefonica/webview-bridge#146]
Due to the new requirement to be able to generate invoices and that they can be downloaded by the user. It is necessary to create a new bridge method. These files could be of any type (pdfs, zips or any other file types).

MIME type will be extracted from file extension.

Behaviour of this method is similar than the SHARE_BASE64 existing one, however, it changes on how the processed file is handled afterwards.

#### Android

1. Once file is correctly processed, a "Downloaded" notification is shown in the system notifications inbox. System will try to open the file when clicking on it.
2. Simultaneously, app will try to open the given file, this may result in 3 situations:
    - No app that can handle this type of file is available
        - Nothing will happen, user feedback will be just the previous generated notification.
    - Multiple apps can handle this type of file
        - System will show a desambiguator window to select the app which will be used to open the file.
    - Single app can open this type of file (Or an app is set as default for these kind of files)
        - App will be presented immediatly with the donwloaded content.

https://github.com/user-attachments/assets/6feaed05-89f2-467b-b017-dc966bae1213

#### iOS

The behavior will be similar to the current webview download mode but downloading the file before showing it

1.- Once the file is correctly procesed, it will be stored in a tmp directory
2.- The app will open a modal webview presenting the local file in a web browser similar to the one used in download webview mode but hiding the "Open in Safari" button (due to no sense for a local file).

https://github.com/user-attachments/assets/66726efd-4867-4c08-997e-a85f9cfb7c31

### Js Method

```javascript
downloadBase64: ({ content: string, fileName: string }) => Promise<void>
Request → { type: "DOWNLOAD_BASE64", id: string, payload: { content: "base64 string", fileName: "fileName.ext" } } 
Response → { type: "DOWNLOAD_BASE64", id: string }
```

**Note: Custom title we talked about would be just the filename with its extension, as tipically, pdf apps (or for other files) will tipically show as title this filename (or any other thing included as part of the specific file format as title.)**

**Note: filename must contain extension, so apps can determine proper MIME type.**

### Success response
Empty response. Response be always sent after file has been processed and it has been sent to the system to open it, as in case of an error processing the file, an error response will be sent.

### Error response codes
400 → Bad request: If payload is null or there's any missing mandatory parameter.
500 → Internal Error: If an error occurred while processing the file

**Comment by atabel** [comment]
WEB ticket https://jira.tid.es/browse/WEB-2037
