### ISSUE TITLE
New method to get the battery status.

### ISSUE THREAD

**Issue by L-Trujillo26** [Telefonica/webview-bridge#148]
Due to [this spec](https://telefonicacorp.sharepoint.com/:w:/s/Colabora_TCX/EcQggw2nK3VHt_EuM0yzXIIBtFgsW8vJS2_zs77Cmp4UzQ?e=WTvegl&wdOrigin=TEAMS-MAGLEV.p2p_ns.rwc&wdExp=TEAMS-TREATMENT&wdhostclicktime=1727275474099&web=1) from Vivo, we need to implement functionality to provide the device's battery status. This will help enhance the user experience during eSIM-related activities.

**Details**:
The implementation should provide the following information:

**- Battery Level**: The current battery percentage. (optional if the battery information is unavailable).
**- Power Save Mode**: Whether the device has power-saving mode enabled.

Get Battery information

`getBatteryInfo: () => Promise<{batteryLevel: int? | null, isPowerSaveMode: boolean}>`

```
Request → {type: "GET_BATTERY_INFO", id: string} 
Response → {type: "GET_BATTERY_INFO", id: string, payload: {batteryLevel?: 90, isPowerSaveMode: true }}
```

For efficiency and data consistency, we have proposed implementing a single method via the bridge that returns both the battery level and the power-saving mode status together. However, it is also possible to implement two separate methods.

**Comment by atabel** [comment]
please, use camelCase for `batteryLevel`

**Comment by L-Trujillo26** [comment]
done

> please, use camelCase for `batteryLevel`
