### ISSUE TITLE
Clipboard access

### ISSUE THREAD

**Issue by jeprubio** [Telefonica/webview-bridge#149]
Due this [jira task OBVIVO-2111](https://jira.tid.es/browse/OBVIVO-2111), vivo needs to access to the clipboard from android and can't at the moment.

When the web tries to access the clipboard from the app it gets an error message about missing permissions, after some research it seems the best way to do that is to use a javascript bridge and use native code for that as seen in [Clipboard API call throws NotAllowedError without invoking onPermissionRequest()](https://stackoverflow.com/questions/61243646/clipboard-api-call-throws-notallowederror-without-invoking-onpermissionrequest/61546346#61546346).

A possible solution would include a couple of bridge methods:

## Read from the clipboard

This method allows to read text from the clipboard.

### Js method
```javascript
clipboardRead: ({}) => Promise<string>
Request → { type: "CLIPBOARD_READ_TEXT", id: string }
Response → { type: "CLIPBOARD_READ_TEXT", id: string, payload: "Parcela PIX" }
```

Message type:

**CLIPBOARD_READ_TEXT**

### Success response
Response with the text from the clipboard. Empty string if it's empty.

## Copy/Write to the clipboard

This method allows to copy text to the clipboard.

In case it is called when the loading screen is not currently shown, it would have no effect.

### Js method
```javascript
clipboardWrite: ({
    message: string;
}) => Promise<void>
Request → { type: "CLIPBOARD_WRITE_TEXT", id: string, payload: "Parcela PIX" }
Response → { type: "CLIPBOARD_WRITE_TEXT", id: string }
```

Message type:

**CLIPBOARD_WRITE_TEXT**

### Success response
Empty response.

### Error response codes
400 → Bad request: If payload is null or it contains no message to copy.
500 → Internal Error: If an error occurred while copying the text to the clipboard.

This could be added in 24.10

**Comment by atabel** [comment]
https://jira.tid.es/browse/WEB-2063

**Comment by atabel** [comment]
@jeprubio, please document the request/response messages shape, I guess the response payload is just a string?
We also need a min app version to include it in the final docs

**Comment by jeprubio** [comment]
> @jeprubio, please document the request/response messages shape, I guess the response payload is just a string? We also need a min app version to include it in the final docs

I see, added. I've also added this could be done for 24.10 but I'm opened to suggestions if anybody thinks it's too soon.

**Comment by atabel** [comment]
I think READ response and WRITE request messages should be symmetric
```
Response → { type: "CLIPBOARD_READ_TEXT", id: string, payload: "Parcela PIX" }
```
vs
```
Request → { type: "CLIPBOARD_WRITE_TEXT", id: string, payload: { message: "Parcela PIX" } }
```

If the payload is an string it should be an string in both, why use an string for READ response payload and an object for WRITE request payload?

**Comment by jeprubio** [comment]
> I think READ response and WRITE request messages should be symmetric
> 
> ```
> Response → { type: "CLIPBOARD_READ_TEXT", id: string, payload: "Parcela PIX" }
> ```
> 
> vs
> 
> ```
> Request → { type: "CLIPBOARD_WRITE_TEXT", id: string, payload: { message: "Parcela PIX" } }
> ```
> 
> If the payload is an string it should be an string in both, why use an string for READ response payload and an object for WRITE request payload?

Fair, updated.
