### ISSUE TITLE
New method to validate datamob requirements

### ISSUE THREAD

**Issue by DevPabloGarcia** [Telefonica/webview-bridge#172]
**Message type**: `VALIDATE_DATAMOB_REQUIREMENTS`

**Originator**: Web

## Description

In order to accomplish the new datamob functionality for VIVO ([APPS-8195](https://jira.tid.es/browse/APPS-8195), [PRD](https://confluence.tid.es/display/CTO/Tech+Spec+-+Datamob+project)) we need to implement a new bridge method to check if all requirements are valid.

This new method will return a map with the requirements. Each requirement is a boolean value where true is valid, false is not valid.

### Datamob SDK explanation
Datamob is a library that offer developers an easy and efficient way to integrate security and remote device control features into their applications.
Datamob integration enables the registration of a user, which consists of a phone number, a token-type password and a random hash generated at the time of registration. This process is performed through API calls, which requires an active internet connection. Once the user is registered in the DeviceSeguro system, the associated device will be enabled to receive and execute remote security commands.

These remote commands include actions such as locking the device screen (lock screen) or even forcing a wipe (factory reset) of the device, providing additional security control for the end user.

The Datamob library is ideal for developers who want to incorporate advanced security features into their applications, facilitating the implementation of remote control and secure device management.

## Differences between iOS/Android (if any)

N/A

## Payload definition

**Request Payload**  
```ts
{
    phoneNumber: string; // The user phone number
    tokenPassword: string; // When registering the device, datamob generate an accessKey that is recorded in the Datamob device registry. By combining this attribute with a hash that we keep in a password vault, generate this token.
}
```

Examples

```json
{
    "type": "VALIDATE_DATAMOB_REQUIREMENTS",
    "id": "id",
    "payload": {
        "phoneNumber": "phone_number",
        "token": "password_token"
    }
}
```

**Response Payload**  
```ts
{
    requirements: {
      deviceAdmin: boolean;
      googleAccount: boolean;
      lockPassword: boolean;
      accessibilityOption: boolean;
      invalidPhoneNumber: boolean;
      invalidToken: boolean;
    }
}

```

Examples:

```json
{
    "type": "VALIDATE_DATAMOB_REQUIREMENTS", 
    "payload": { 
        "requirements": {
            "deviceAdmin" : false,
            "googleAccount" : true,
            "lockPassword" : false,
            "accessibilityOption" : true,
            "invalidPhoneNumber" : true,
            "invalidToken" : true
        }    
    }
}
```

## Possible error cases
400 - If phoneNumber or tokenPassword are empty

**Comment by dzayas** [comment]
Just a comment about the naming, maybe is not self-explained that the returned enum, are the requirements that aren't valid. Maybe we can send the full map with:

prerequisite -> status (bool)?

**Comment by DevPabloGarcia** [comment]
@dzayas Modified
@atabel modified payload definition to match with the example

**Comment by atabel** [comment]
> If all requirements are valid, the method will return an empty list.

Is this wrong?
According to the response payload, the result is always a map of prerequisite -> boolean

**Comment by DevPabloGarcia** [comment]
@atabel Modified prerequisites to -> requirements and updated return explain text

**Comment by dzayas** [comment]
In the response payload it should "invalidPhonenumber" instead of "invalidPassword" right?

**Comment by DevPabloGarcia** [comment]
@dzayas Modified invalidPassword to invalidPhoneNumber
