### ISSUE TITLE
New bridge method to register user in Datamob SDK

### ISSUE THREAD

**Issue by DevPabloGarcia** [Telefonica/webview-bridge#174]
**Message type**: `REGISTER_DATAMOB_USER`

**Originator**: web

## Description

The application that implements the Datamob should have an user registered. This SDK provide a method to make this register.

This data must be provided at the time of registration, as parameters for the Register method.

## Differences between iOS/Android (if any)
N/A

## Payload definition

**Request Payload**  

```ts
{
    phoneNumber: string; // The user phone number
    tokenPassword: string; // When registering the device, datamob generate an accessKey that is recorded in the Datamob device registry. By combining this attribute with a hash that we keep in a password vault, generate this token.
}
```

Examples:

```json
{
    "type": "REGISTER_DATAMOB_USER",
    "id": "id", 
    "payload": {
        "phoneNumber": "601234567",
        "tokenPassword": "token_password"
    }
}
```

**Response Payload**  

```ts
void
```

Examples:

```json
{
    "type": "REGISTER_DATAMOB_USER",
    "id": "id"
}
```

## Possible error cases
500 -> "Registration error: '$exception.message' "

**Comment by atabel** [comment]
WEB jira ticket to implement this: https://jira.tid.es/browse/WEB-2112
