### ISSUE TITLE
New bridge method to show Qualtrics survey

### ISSUE THREAD

**Issue by dhidalgofadrique** [Telefonica/webview-bridge#178]
**Message type**: `DISPLAY_QUALTRICS_INTERCEPT`

**Originator**: Web

**Min app version**: 24.12

## Description

In order to accomplish the integration of the Qualtrics SDK for VIVO ([APPS-8203](https://jira.tid.es/browse/APPS-8203)) we need to implement a new bridge method to show (if possible) a suervey to the user using this SDK.

This new method will provide an interceptor id in the request. If provided the app will try to show the survey related to this intercept id.

It will return a boolean indicating if the survey has been displayed or not (

## Differences between iOS/Android (if any)

N/A

## Payload definition

**Request Payload**
```ts
{
    intercetptId: string;
}
```

Examples:

```json
{
    "type": "DISPLAY_QUALTRICS_INTERCEPT",
    "id": "id-display-qualtrics-intercept",
    "payload": {
        "intercetptId": "SI_81gUpIN3UhXAZU2"
    }
}
```

**Response Payload**
```ts
{
    displayed: boolean;
}
```

Examples:

```json
{
    "type": "DISPLAY_QUALTRICS_INTERCEPT",
    "id": "id-display-qualtrics-intercept",
    "payload": {
        "displayed": true
    }
}
```

## Possible error cases

500 → Internal Error: If an error occurred invoking the SDK
501 → SDK not initialized

**Comment by atabel** [comment]
Web ticket https://jira.tid.es/browse/WEB-2119

**Comment by dzayas** [comment]
intercetpId is declared as boolean here, and it should be String, right?

**Comment by dhidalgofadrique** [comment]
> intercetpId is declared as boolean here, and it should be String, right?

Right. Updated description
