### ISSUE TITLE
New bridge method to set Qualtrics properties

### ISSUE THREAD

**Issue by dhidalgofadrique** [Telefonica/webview-bridge#179]
**Message type**: `SET_QUALTRICS_PROPERTIES`

**Originator**: Web

**Min app version**: 24.12

## Description

In order to accomplish the integration of the Qualtrics SDK for VIVO ([APPS-8203](https://jira.tid.es/browse/APPS-8203)) we need to implement a new bridge method to set properties in Qualtrics SDK.

Due to the SDK has three different methods to set properties depending on its type and to avoid having multiple bridge methods, tha approach is passing in the request a struct containing three arrays for each property type: string, number and dateTime. This way, this method will allow setting multiple properties with one call and avoids using generic types and casting that may produce undesired errors.

Number and string properties require a value of the corresponding type (number or string) and a key to identify the property where the value is going to be set.

Date time properties only require a key to identify the property where the value is going to be set. This value will be a timestamp.

## Differences between iOS/Android (if any)

N/A

## Payload definition

**Request Payload**  

```ts
{
    stringProperties: [{key: string, value: string}],
    numberProperties:  [{key: string, value: number}],
    dateTimePropertyKeys: string[]
}
```

Examples:

```json
{
    "type": "SET_QUALTRICS_PROPERTIES", 
    "id": "id-set-qualtrics-properties",
    "payload": {
        "stringProperties": [
            {
                "key": "stringProperty1",
                "value": "Test value 1"
            },
            {
                "key": "stringProperty2",
                "value": "Test value 2"
            },
        ],
        "numberProperties": [
            {
                "key": "numericProperty",
                "value": 12.0
            }
        ],
        "dateTimePropertyKeys": ["dateTimePropertyKey"]
    }
}
```

**Response Payload**  
No payload required

Examples:

```json
{
    "type": "SET_QUALTRICS_PROPERTIES", 
    "id": "id-set-qualtrics-properties"
}
```

## Possible error cases

500 → Internal Error: If an error occurred invoking the SDK
501 → SDK not initialized

**Comment by atabel** [comment]
web ticket https://jira.tid.es/browse/WEB-2119

**Comment by atabel** [comment]
Change in the payload definition to match the types expected by the iOS app which is already implemented:

## Payload definition

**Request Payload**  

```ts
{
    stringProperties: {[key: string]: string},
    numberProperties: {[key: string]: number},
    dateTimePropertyKeys: string[]
}
```

Examples:

```json
{
    "type": "SET_QUALTRICS_PROPERTIES", 
    "id": "id-set-qualtrics-properties",
    "payload": {
        "stringProperties": {
            "stringProperty1": "Test value 1",
            "stringProperty2": "Test value 2"
        },
        "numberProperties": {
            "numericProperty": 12
        },
        "dateTimePropertyKeys": ["dateTimePropertyKey"]
    }
}
```
