### ISSUE TITLE
New Bridge Method unregisterAdmin

### ISSUE THREAD

**Issue by DevPabloGarcia** [Telefonica/webview-bridge#182]
**Message type**: `UNREGISTER_DATAMOB_DEVICE_ADMIN`

**Originator**: Web

## Description

The application that implements the Datamob library must let the possibility to unregister app as admin.
The library also provides a method to assist with this unregistration.

## Differences between iOS/Android (if any)
N/A

## Payload definition

**Request Payload**  

```ts
No params
```

**Response Payload**  
```ts
void
```

Examples:

```json
{
    "type": "UNREGISTER_DATAMOB_DEVICE_ADMIN", 
    "id": "web-2"
}
```

## Possible error cases
500 -> "Unregister admin error: '$exception.message' "

**Comment by dzayas** [comment]
Hi, does this unregister action follow the same way that registerAction?

https://github.com/Telefonica/webview-bridge/issues/175

I mean, it is asked confirmation to the user, or directly is unregistered and the bridge returns true/false? I said that to check if it worth to follow the same naming that for regiter method that returns isAdmin as return param.

**Comment by DevPabloGarcia** [comment]
It directly unregister without showing any confirmation screen @dzayas

**Comment by dzayas** [comment]
OK, thanks for the explanation. Yes i think that we can follow the register function way. No response payload + http error code.

**Comment by atabel** [comment]
web ticket https://jira.tid.es/browse/WEB-2123
